export type RootStackParamList = {
  Splash: undefined;
  Onboarding1: undefined;
  Onboarding2: undefined;
  Onboarding3: undefined;
  Login: undefined;
  TermsUpdate: undefined;
  BuyCredit: undefined;
  BasicDetails: undefined;
  PartnerDocuments: undefined;
  ApplicationProcessing: undefined;
  Permissions: undefined;
  Verification: undefined;
  MainTabs: undefined;
  Vehicle: undefined;
  Payouts: undefined;
  Wallet: undefined;
  TripDetail: { tripId: string };
  Settings: undefined;
  SOS: undefined;
  Logout: undefined;
  Documents: undefined;
  DocumentDetail: { docId: string };
  RideRequest: undefined;
  PickupNav: undefined;
  Arrived: undefined;
  LiveTrip: undefined;
  TripEarnings: undefined;
  PassengerRating: undefined;
};
